services:
  - type: web
    name: lung-cancer-detection
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements_streamlit.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: lung-cancer-db
          property: connectionString
    
databases:
  - name: lung-cancer-db
    databaseName: lung_cancer_detection
    user: app_user