[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "#2ee6ff"
backgroundColor = "#070b12"
secondaryBackgroundColor = "#0e141f"
textColor = "#e7eef6"
font = "sans serif"

[client]
showSidebarNavigation = false
